# frontend/Dockerfile.dev
FROM node:20.18.3-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

ENV NEXT_PUBLIC_API_URL=http://localhost:8080/api

EXPOSE 3000

CMD ["npm", "run", "dev"]
